# Uncomment the next line to define a global platform for your project
 platform :ios, '12.1'

target 'hICNTools' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Charts'
  # Pods for hICNTools

end
workspace 'hICNTools'
